//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartschoolServiceClient.SmartschoolService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://piso.smartschool.be/Webservices/V3", ConfigurationName="SmartschoolService.V3Port")]
    public interface V3Port {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object saveUser(
                    string accesscode, 
                    string internnumber, 
                    string username, 
                    string passwd1, 
                    string passwd2, 
                    string passwd3, 
                    string name, 
                    string surname, 
                    string extranames, 
                    string initials, 
                    string sex, 
                    string birthday, 
                    string birthplace, 
                    string birthcountry, 
                    string address, 
                    string postalcode, 
                    string location, 
                    string country, 
                    string email, 
                    string mobilephone, 
                    string homephone, 
                    string fax, 
                    string prn, 
                    string stamboeknummer, 
                    string basisrol, 
                    string untis);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveUser", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveUserAsync(
                    string accesscode, 
                    string internnumber, 
                    string username, 
                    string passwd1, 
                    string passwd2, 
                    string passwd3, 
                    string name, 
                    string surname, 
                    string extranames, 
                    string initials, 
                    string sex, 
                    string birthday, 
                    string birthplace, 
                    string birthcountry, 
                    string address, 
                    string postalcode, 
                    string location, 
                    string country, 
                    string email, 
                    string mobilephone, 
                    string homephone, 
                    string fax, 
                    string prn, 
                    string stamboeknummer, 
                    string basisrol, 
                    string untis);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object saveClass(string accesscode, string name, string desc, string code, string parent, string untis, string instituteNumber, string adminNumber, string schoolYearDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveClass", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveClassAsync(string accesscode, string name, string desc, string code, string parent, string untis, string instituteNumber, string adminNumber, string schoolYearDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#changeGroupVisibility", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object changeGroupVisibility(string accesscode, string code, int visbility);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#changeGroupVisibility", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> changeGroupVisibilityAsync(string accesscode, string code, int visbility);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object saveGroup(string accesscode, string name, string desc, string code, string parent, string untis);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveGroup", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveGroupAsync(string accesscode, string name, string desc, string code, string parent, string untis);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAllAccounts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object getAllAccounts(string accesscode, string code, string recursive);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAllAccounts", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getAllAccountsAsync(string accesscode, string code, string recursive);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAllAccountsExtended", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object getAllAccountsExtended(string accesscode, string code, string recursive);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAllAccountsExtended", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getAllAccountsExtendedAsync(string accesscode, string code, string recursive);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAllGroupsAndClasses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object getAllGroupsAndClasses(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAllGroupsAndClasses", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getAllGroupsAndClassesAsync(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#addCourse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string addCourse(string accesscode, string coursename, string coursedesc, int visibility);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#addCourse", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> addCourseAsync(string accesscode, string coursename, string coursedesc, int visibility);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#addCourseTeacher", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object addCourseTeacher(string accesscode, string coursename, string coursedesc, string internnummer, string userlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#addCourseTeacher", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> addCourseTeacherAsync(string accesscode, string coursename, string coursedesc, string internnummer, string userlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#addCourseStudents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object addCourseStudents(string accesscode, string coursename, string coursedesc, string groupIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#addCourseStudents", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> addCourseStudentsAsync(string accesscode, string coursename, string coursedesc, string groupIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getCourses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getCourses(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getCourses", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCoursesAsync(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#delUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object delUser(string accesscode, string userIdentifier, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#delUser", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> delUserAsync(string accesscode, string userIdentifier, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveUserParameter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object saveUserParameter(string accesscode, string userIdentifier, string paramName, string paramValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveUserParameter", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveUserParameterAsync(string accesscode, string userIdentifier, string paramName, string paramValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getClassList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getClassList(object accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getClassList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getClassListAsync(object accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getClassListJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getClassListJson(object accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getClassListJson", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getClassListJsonAsync(object accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveClassList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object saveClassList(string accesscode, string serializedList);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveClassList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveClassListAsync(string accesscode, string serializedList);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveClassListJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object saveClassListJson(string accesscode, string jsonList);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveClassListJson", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveClassListJsonAsync(string accesscode, string jsonList);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#delClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object delClass(string accesscode, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#delClass", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> delClassAsync(string accesscode, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveUserToClasses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object saveUserToClasses(string accesscode, string userIdentifier, string csvList);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveUserToClasses", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveUserToClassesAsync(string accesscode, string userIdentifier, string csvList);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#removeUserFromGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object removeUserFromGroup(string accesscode, string userIdentifier, string @class, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#removeUserFromGroup", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> removeUserFromGroupAsync(string accesscode, string userIdentifier, string @class, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#clearGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object clearGroup(string accesscode, string group, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#clearGroup", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> clearGroupAsync(string accesscode, string group, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveUserToClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object saveUserToClass(string accesscode, string userIdentifier, string @class, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveUserToClass", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveUserToClassAsync(string accesscode, string userIdentifier, string @class, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveUserToClassesAndGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object saveUserToClassesAndGroups(string accesscode, string userIdentifier, string csvList, int keepOld);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveUserToClassesAndGroups", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveUserToClassesAndGroupsAsync(string accesscode, string userIdentifier, string csvList, int keepOld);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#setAccountStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object setAccountStatus(string accesscode, string userIdentifier, object accountStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#setAccountStatus", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> setAccountStatusAsync(string accesscode, string userIdentifier, object accountStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#setAccountPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object setAccountPhoto(string accesscode, string userIdentifier, string photo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#setAccountPhoto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> setAccountPhotoAsync(string accesscode, string userIdentifier, string photo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAccountPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAccountPhoto(string accesscode, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAccountPhoto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAccountPhotoAsync(string accesscode, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#replaceInum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object replaceInum(string accesscode, string oldInum, string newInum);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#replaceInum", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> replaceInumAsync(string accesscode, string oldInum, string newInum);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#forcePasswordReset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object forcePasswordReset(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#forcePasswordReset", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> forcePasswordResetAsync(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#savePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object savePassword(string accesscode, string userIdentifier, string password, int accountType, int changePasswordAtNextLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#savePassword", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> savePasswordAsync(string accesscode, string userIdentifier, string password, int accountType, int changePasswordAtNextLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#changePasswordAtNextLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object changePasswordAtNextLogin(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#changePasswordAtNextLogin", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> changePasswordAtNextLoginAsync(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#sendMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object sendMsg(string accesscode, string userIdentifier, string title, string body, string senderIdentifier, object attachments, int coaccount, bool copyToLVS);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#sendMsg", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> sendMsgAsync(string accesscode, string userIdentifier, string title, string body, string senderIdentifier, object attachments, int coaccount, bool copyToLVS);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getSkoreClassTeacherCourseRelation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object getSkoreClassTeacherCourseRelation(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getSkoreClassTeacherCourseRelation", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getSkoreClassTeacherCourseRelationAsync(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#unregisterStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object unregisterStudent(string accesscode, string userIdentifier, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#unregisterStudent", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> unregisterStudentAsync(string accesscode, string userIdentifier, string officialDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getClassTeachers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object getClassTeachers(string accesscode, bool getAllOwners);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getClassTeachers", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getClassTeachersAsync(string accesscode, bool getAllOwners);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAbsentsByDate(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsByDate", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsByDateAsync(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsWithInternalNumberByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAbsentsWithInternalNumberByDate(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsWithInternalNumberByDate", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsWithInternalNumberByDateAsync(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsWithUsernameByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAbsentsWithUsernameByDate(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsWithUsernameByDate", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsWithUsernameByDateAsync(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsByDateAndGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAbsentsByDateAndGroup(string accesscode, string date, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsByDateAndGroup", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsByDateAndGroupAsync(string accesscode, string date, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsWithAliasByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAbsentsWithAliasByDate(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsWithAliasByDate", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsWithAliasByDateAsync(string accesscode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAbsents(string accesscode, string userIdentifier, string schoolYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsents", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsAsync(string accesscode, string userIdentifier, string schoolYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsWithAlias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAbsentsWithAlias(string accesscode, string userIdentifier, string schoolYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getAbsentsWithAlias", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAbsentsWithAliasAsync(string accesscode, string userIdentifier, string schoolYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getUserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getUserDetails(string accesscode, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getUserDetails", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getUserDetailsAsync(string accesscode, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getUserDetailsByNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getUserDetailsByNumber(string accesscode, string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getUserDetailsByNumber", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getUserDetailsByNumberAsync(string accesscode, string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getUserDetailsByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getUserDetailsByUsername(string accesscode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getUserDetailsByUsername", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getUserDetailsByUsernameAsync(string accesscode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getUserDetailsByScannableCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getUserDetailsByScannableCode(string accesscode, string scannableCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getUserDetailsByScannableCode", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getUserDetailsByScannableCodeAsync(string accesscode, string scannableCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getUserOfficialClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getUserOfficialClass(string accesscode, string userIdentifier, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getUserOfficialClass", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getUserOfficialClassAsync(string accesscode, string userIdentifier, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveSignature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool saveSignature(string accesscode, string userIdentifier, int accountType, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveSignature", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> saveSignatureAsync(string accesscode, string userIdentifier, int accountType, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getStudentCareer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getStudentCareer(string accesscode, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getStudentCareer", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getStudentCareerAsync(string accesscode, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#deactivateTwoFactorAuthentication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object deactivateTwoFactorAuthentication(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#deactivateTwoFactorAuthentication", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> deactivateTwoFactorAuthenticationAsync(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="https://piso.smartschool.be/Webservices/V3#returnErrorCodes")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void returnErrorCodes();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="https://piso.smartschool.be/Webservices/V3#returnErrorCodes")]
        System.Threading.Tasks.Task returnErrorCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#returnCsvErrorCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string returnCsvErrorCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#returnCsvErrorCodes", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> returnCsvErrorCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#returnJsonErrorCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string returnJsonErrorCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#returnJsonErrorCodes", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> returnJsonErrorCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#startSkoreSync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string startSkoreSync(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#startSkoreSync", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> startSkoreSyncAsync(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#checkStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string checkStatus(string accesscode, string serviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#checkStatus", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> checkStatusAsync(string accesscode, string serviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#changeUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int changeUsername(string accesscode, string internNumber, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#changeUsername", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> changeUsernameAsync(string accesscode, string internNumber, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#changeInternNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int changeInternNumber(string accesscode, string username, string newInternNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#changeInternNumber", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> changeInternNumberAsync(string accesscode, string username, string newInternNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#changeGroupOwners", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int changeGroupOwners(string accesscode, string code, string userlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#changeGroupOwners", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> changeGroupOwnersAsync(string accesscode, string code, string userlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#removeCoAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object removeCoAccount(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#removeCoAccount", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> removeCoAccountAsync(string accesscode, string userIdentifier, int accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getSchoolyearDataOfClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object getSchoolyearDataOfClass(string accesscode, string classCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getSchoolyearDataOfClass", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getSchoolyearDataOfClassAsync(string accesscode, string classCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveSchoolyearDataOfClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object saveSchoolyearDataOfClass(string accesscode, string classCode, string date, string instituteNumber, string administrativeGroupNumber, string residence, string domain, string principal);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#saveSchoolyearDataOfClass", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> saveSchoolyearDataOfClassAsync(string accesscode, string classCode, string date, string instituteNumber, string administrativeGroupNumber, string residence, string domain, string principal);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getDeliberationLines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object getDeliberationLines(string accesscode, string dateInSchoolYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getDeliberationLines", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getDeliberationLinesAsync(string accesscode, string dateInSchoolYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#addHelpdeskTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object addHelpdeskTicket(string accesscode, string title, string description, int priority, string miniDbItem, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#addHelpdeskTicket", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> addHelpdeskTicketAsync(string accesscode, string title, string description, int priority, string miniDbItem, string userIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getHelpdeskMiniDbItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object getHelpdeskMiniDbItems(string accesscode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://piso.smartschool.be/Webservices/V3#getHelpdeskMiniDbItems", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> getHelpdeskMiniDbItemsAsync(string accesscode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface V3PortChannel : SmartschoolServiceClient.SmartschoolService.V3Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class V3PortClient : System.ServiceModel.ClientBase<SmartschoolServiceClient.SmartschoolService.V3Port>, SmartschoolServiceClient.SmartschoolService.V3Port {
        
        public V3PortClient() {
        }
        
        public V3PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public V3PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public V3PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public V3PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object saveUser(
                    string accesscode, 
                    string internnumber, 
                    string username, 
                    string passwd1, 
                    string passwd2, 
                    string passwd3, 
                    string name, 
                    string surname, 
                    string extranames, 
                    string initials, 
                    string sex, 
                    string birthday, 
                    string birthplace, 
                    string birthcountry, 
                    string address, 
                    string postalcode, 
                    string location, 
                    string country, 
                    string email, 
                    string mobilephone, 
                    string homephone, 
                    string fax, 
                    string prn, 
                    string stamboeknummer, 
                    string basisrol, 
                    string untis) {
            return base.Channel.saveUser(accesscode, internnumber, username, passwd1, passwd2, passwd3, name, surname, extranames, initials, sex, birthday, birthplace, birthcountry, address, postalcode, location, country, email, mobilephone, homephone, fax, prn, stamboeknummer, basisrol, untis);
        }
        
        public System.Threading.Tasks.Task<object> saveUserAsync(
                    string accesscode, 
                    string internnumber, 
                    string username, 
                    string passwd1, 
                    string passwd2, 
                    string passwd3, 
                    string name, 
                    string surname, 
                    string extranames, 
                    string initials, 
                    string sex, 
                    string birthday, 
                    string birthplace, 
                    string birthcountry, 
                    string address, 
                    string postalcode, 
                    string location, 
                    string country, 
                    string email, 
                    string mobilephone, 
                    string homephone, 
                    string fax, 
                    string prn, 
                    string stamboeknummer, 
                    string basisrol, 
                    string untis) {
            return base.Channel.saveUserAsync(accesscode, internnumber, username, passwd1, passwd2, passwd3, name, surname, extranames, initials, sex, birthday, birthplace, birthcountry, address, postalcode, location, country, email, mobilephone, homephone, fax, prn, stamboeknummer, basisrol, untis);
        }
        
        public object saveClass(string accesscode, string name, string desc, string code, string parent, string untis, string instituteNumber, string adminNumber, string schoolYearDate) {
            return base.Channel.saveClass(accesscode, name, desc, code, parent, untis, instituteNumber, adminNumber, schoolYearDate);
        }
        
        public System.Threading.Tasks.Task<object> saveClassAsync(string accesscode, string name, string desc, string code, string parent, string untis, string instituteNumber, string adminNumber, string schoolYearDate) {
            return base.Channel.saveClassAsync(accesscode, name, desc, code, parent, untis, instituteNumber, adminNumber, schoolYearDate);
        }
        
        public object changeGroupVisibility(string accesscode, string code, int visbility) {
            return base.Channel.changeGroupVisibility(accesscode, code, visbility);
        }
        
        public System.Threading.Tasks.Task<object> changeGroupVisibilityAsync(string accesscode, string code, int visbility) {
            return base.Channel.changeGroupVisibilityAsync(accesscode, code, visbility);
        }
        
        public object saveGroup(string accesscode, string name, string desc, string code, string parent, string untis) {
            return base.Channel.saveGroup(accesscode, name, desc, code, parent, untis);
        }
        
        public System.Threading.Tasks.Task<object> saveGroupAsync(string accesscode, string name, string desc, string code, string parent, string untis) {
            return base.Channel.saveGroupAsync(accesscode, name, desc, code, parent, untis);
        }
        
        public object getAllAccounts(string accesscode, string code, string recursive) {
            return base.Channel.getAllAccounts(accesscode, code, recursive);
        }
        
        public System.Threading.Tasks.Task<object> getAllAccountsAsync(string accesscode, string code, string recursive) {
            return base.Channel.getAllAccountsAsync(accesscode, code, recursive);
        }
        
        public object getAllAccountsExtended(string accesscode, string code, string recursive) {
            return base.Channel.getAllAccountsExtended(accesscode, code, recursive);
        }
        
        public System.Threading.Tasks.Task<object> getAllAccountsExtendedAsync(string accesscode, string code, string recursive) {
            return base.Channel.getAllAccountsExtendedAsync(accesscode, code, recursive);
        }
        
        public object getAllGroupsAndClasses(string accesscode) {
            return base.Channel.getAllGroupsAndClasses(accesscode);
        }
        
        public System.Threading.Tasks.Task<object> getAllGroupsAndClassesAsync(string accesscode) {
            return base.Channel.getAllGroupsAndClassesAsync(accesscode);
        }
        
        public string addCourse(string accesscode, string coursename, string coursedesc, int visibility) {
            return base.Channel.addCourse(accesscode, coursename, coursedesc, visibility);
        }
        
        public System.Threading.Tasks.Task<string> addCourseAsync(string accesscode, string coursename, string coursedesc, int visibility) {
            return base.Channel.addCourseAsync(accesscode, coursename, coursedesc, visibility);
        }
        
        public object addCourseTeacher(string accesscode, string coursename, string coursedesc, string internnummer, string userlist) {
            return base.Channel.addCourseTeacher(accesscode, coursename, coursedesc, internnummer, userlist);
        }
        
        public System.Threading.Tasks.Task<object> addCourseTeacherAsync(string accesscode, string coursename, string coursedesc, string internnummer, string userlist) {
            return base.Channel.addCourseTeacherAsync(accesscode, coursename, coursedesc, internnummer, userlist);
        }
        
        public object addCourseStudents(string accesscode, string coursename, string coursedesc, string groupIds) {
            return base.Channel.addCourseStudents(accesscode, coursename, coursedesc, groupIds);
        }
        
        public System.Threading.Tasks.Task<object> addCourseStudentsAsync(string accesscode, string coursename, string coursedesc, string groupIds) {
            return base.Channel.addCourseStudentsAsync(accesscode, coursename, coursedesc, groupIds);
        }
        
        public string getCourses(string accesscode) {
            return base.Channel.getCourses(accesscode);
        }
        
        public System.Threading.Tasks.Task<string> getCoursesAsync(string accesscode) {
            return base.Channel.getCoursesAsync(accesscode);
        }
        
        public object delUser(string accesscode, string userIdentifier, string officialDate) {
            return base.Channel.delUser(accesscode, userIdentifier, officialDate);
        }
        
        public System.Threading.Tasks.Task<object> delUserAsync(string accesscode, string userIdentifier, string officialDate) {
            return base.Channel.delUserAsync(accesscode, userIdentifier, officialDate);
        }
        
        public object saveUserParameter(string accesscode, string userIdentifier, string paramName, string paramValue) {
            return base.Channel.saveUserParameter(accesscode, userIdentifier, paramName, paramValue);
        }
        
        public System.Threading.Tasks.Task<object> saveUserParameterAsync(string accesscode, string userIdentifier, string paramName, string paramValue) {
            return base.Channel.saveUserParameterAsync(accesscode, userIdentifier, paramName, paramValue);
        }
        
        public string getClassList(object accesscode) {
            return base.Channel.getClassList(accesscode);
        }
        
        public System.Threading.Tasks.Task<string> getClassListAsync(object accesscode) {
            return base.Channel.getClassListAsync(accesscode);
        }
        
        public string getClassListJson(object accesscode) {
            return base.Channel.getClassListJson(accesscode);
        }
        
        public System.Threading.Tasks.Task<string> getClassListJsonAsync(object accesscode) {
            return base.Channel.getClassListJsonAsync(accesscode);
        }
        
        public object saveClassList(string accesscode, string serializedList) {
            return base.Channel.saveClassList(accesscode, serializedList);
        }
        
        public System.Threading.Tasks.Task<object> saveClassListAsync(string accesscode, string serializedList) {
            return base.Channel.saveClassListAsync(accesscode, serializedList);
        }
        
        public object saveClassListJson(string accesscode, string jsonList) {
            return base.Channel.saveClassListJson(accesscode, jsonList);
        }
        
        public System.Threading.Tasks.Task<object> saveClassListJsonAsync(string accesscode, string jsonList) {
            return base.Channel.saveClassListJsonAsync(accesscode, jsonList);
        }
        
        public object delClass(string accesscode, string code) {
            return base.Channel.delClass(accesscode, code);
        }
        
        public System.Threading.Tasks.Task<object> delClassAsync(string accesscode, string code) {
            return base.Channel.delClassAsync(accesscode, code);
        }
        
        public object saveUserToClasses(string accesscode, string userIdentifier, string csvList) {
            return base.Channel.saveUserToClasses(accesscode, userIdentifier, csvList);
        }
        
        public System.Threading.Tasks.Task<object> saveUserToClassesAsync(string accesscode, string userIdentifier, string csvList) {
            return base.Channel.saveUserToClassesAsync(accesscode, userIdentifier, csvList);
        }
        
        public object removeUserFromGroup(string accesscode, string userIdentifier, string @class, string officialDate) {
            return base.Channel.removeUserFromGroup(accesscode, userIdentifier, @class, officialDate);
        }
        
        public System.Threading.Tasks.Task<object> removeUserFromGroupAsync(string accesscode, string userIdentifier, string @class, string officialDate) {
            return base.Channel.removeUserFromGroupAsync(accesscode, userIdentifier, @class, officialDate);
        }
        
        public object clearGroup(string accesscode, string group, string officialDate) {
            return base.Channel.clearGroup(accesscode, group, officialDate);
        }
        
        public System.Threading.Tasks.Task<object> clearGroupAsync(string accesscode, string group, string officialDate) {
            return base.Channel.clearGroupAsync(accesscode, group, officialDate);
        }
        
        public object saveUserToClass(string accesscode, string userIdentifier, string @class, string officialDate) {
            return base.Channel.saveUserToClass(accesscode, userIdentifier, @class, officialDate);
        }
        
        public System.Threading.Tasks.Task<object> saveUserToClassAsync(string accesscode, string userIdentifier, string @class, string officialDate) {
            return base.Channel.saveUserToClassAsync(accesscode, userIdentifier, @class, officialDate);
        }
        
        public object saveUserToClassesAndGroups(string accesscode, string userIdentifier, string csvList, int keepOld) {
            return base.Channel.saveUserToClassesAndGroups(accesscode, userIdentifier, csvList, keepOld);
        }
        
        public System.Threading.Tasks.Task<object> saveUserToClassesAndGroupsAsync(string accesscode, string userIdentifier, string csvList, int keepOld) {
            return base.Channel.saveUserToClassesAndGroupsAsync(accesscode, userIdentifier, csvList, keepOld);
        }
        
        public object setAccountStatus(string accesscode, string userIdentifier, object accountStatus) {
            return base.Channel.setAccountStatus(accesscode, userIdentifier, accountStatus);
        }
        
        public System.Threading.Tasks.Task<object> setAccountStatusAsync(string accesscode, string userIdentifier, object accountStatus) {
            return base.Channel.setAccountStatusAsync(accesscode, userIdentifier, accountStatus);
        }
        
        public object setAccountPhoto(string accesscode, string userIdentifier, string photo) {
            return base.Channel.setAccountPhoto(accesscode, userIdentifier, photo);
        }
        
        public System.Threading.Tasks.Task<object> setAccountPhotoAsync(string accesscode, string userIdentifier, string photo) {
            return base.Channel.setAccountPhotoAsync(accesscode, userIdentifier, photo);
        }
        
        public string getAccountPhoto(string accesscode, string userIdentifier) {
            return base.Channel.getAccountPhoto(accesscode, userIdentifier);
        }
        
        public System.Threading.Tasks.Task<string> getAccountPhotoAsync(string accesscode, string userIdentifier) {
            return base.Channel.getAccountPhotoAsync(accesscode, userIdentifier);
        }
        
        public object replaceInum(string accesscode, string oldInum, string newInum) {
            return base.Channel.replaceInum(accesscode, oldInum, newInum);
        }
        
        public System.Threading.Tasks.Task<object> replaceInumAsync(string accesscode, string oldInum, string newInum) {
            return base.Channel.replaceInumAsync(accesscode, oldInum, newInum);
        }
        
        public object forcePasswordReset(string accesscode, string userIdentifier, int accountType) {
            return base.Channel.forcePasswordReset(accesscode, userIdentifier, accountType);
        }
        
        public System.Threading.Tasks.Task<object> forcePasswordResetAsync(string accesscode, string userIdentifier, int accountType) {
            return base.Channel.forcePasswordResetAsync(accesscode, userIdentifier, accountType);
        }
        
        public object savePassword(string accesscode, string userIdentifier, string password, int accountType, int changePasswordAtNextLogin) {
            return base.Channel.savePassword(accesscode, userIdentifier, password, accountType, changePasswordAtNextLogin);
        }
        
        public System.Threading.Tasks.Task<object> savePasswordAsync(string accesscode, string userIdentifier, string password, int accountType, int changePasswordAtNextLogin) {
            return base.Channel.savePasswordAsync(accesscode, userIdentifier, password, accountType, changePasswordAtNextLogin);
        }
        
        public object changePasswordAtNextLogin(string accesscode, string userIdentifier, int accountType) {
            return base.Channel.changePasswordAtNextLogin(accesscode, userIdentifier, accountType);
        }
        
        public System.Threading.Tasks.Task<object> changePasswordAtNextLoginAsync(string accesscode, string userIdentifier, int accountType) {
            return base.Channel.changePasswordAtNextLoginAsync(accesscode, userIdentifier, accountType);
        }
        
        public object sendMsg(string accesscode, string userIdentifier, string title, string body, string senderIdentifier, object attachments, int coaccount, bool copyToLVS) {
            return base.Channel.sendMsg(accesscode, userIdentifier, title, body, senderIdentifier, attachments, coaccount, copyToLVS);
        }
        
        public System.Threading.Tasks.Task<object> sendMsgAsync(string accesscode, string userIdentifier, string title, string body, string senderIdentifier, object attachments, int coaccount, bool copyToLVS) {
            return base.Channel.sendMsgAsync(accesscode, userIdentifier, title, body, senderIdentifier, attachments, coaccount, copyToLVS);
        }
        
        public object getSkoreClassTeacherCourseRelation(string accesscode) {
            return base.Channel.getSkoreClassTeacherCourseRelation(accesscode);
        }
        
        public System.Threading.Tasks.Task<object> getSkoreClassTeacherCourseRelationAsync(string accesscode) {
            return base.Channel.getSkoreClassTeacherCourseRelationAsync(accesscode);
        }
        
        public object unregisterStudent(string accesscode, string userIdentifier, string officialDate) {
            return base.Channel.unregisterStudent(accesscode, userIdentifier, officialDate);
        }
        
        public System.Threading.Tasks.Task<object> unregisterStudentAsync(string accesscode, string userIdentifier, string officialDate) {
            return base.Channel.unregisterStudentAsync(accesscode, userIdentifier, officialDate);
        }
        
        public object getClassTeachers(string accesscode, bool getAllOwners) {
            return base.Channel.getClassTeachers(accesscode, getAllOwners);
        }
        
        public System.Threading.Tasks.Task<object> getClassTeachersAsync(string accesscode, bool getAllOwners) {
            return base.Channel.getClassTeachersAsync(accesscode, getAllOwners);
        }
        
        public string getAbsentsByDate(string accesscode, string date) {
            return base.Channel.getAbsentsByDate(accesscode, date);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsByDateAsync(string accesscode, string date) {
            return base.Channel.getAbsentsByDateAsync(accesscode, date);
        }
        
        public string getAbsentsWithInternalNumberByDate(string accesscode, string date) {
            return base.Channel.getAbsentsWithInternalNumberByDate(accesscode, date);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsWithInternalNumberByDateAsync(string accesscode, string date) {
            return base.Channel.getAbsentsWithInternalNumberByDateAsync(accesscode, date);
        }
        
        public string getAbsentsWithUsernameByDate(string accesscode, string date) {
            return base.Channel.getAbsentsWithUsernameByDate(accesscode, date);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsWithUsernameByDateAsync(string accesscode, string date) {
            return base.Channel.getAbsentsWithUsernameByDateAsync(accesscode, date);
        }
        
        public string getAbsentsByDateAndGroup(string accesscode, string date, string code) {
            return base.Channel.getAbsentsByDateAndGroup(accesscode, date, code);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsByDateAndGroupAsync(string accesscode, string date, string code) {
            return base.Channel.getAbsentsByDateAndGroupAsync(accesscode, date, code);
        }
        
        public string getAbsentsWithAliasByDate(string accesscode, string date) {
            return base.Channel.getAbsentsWithAliasByDate(accesscode, date);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsWithAliasByDateAsync(string accesscode, string date) {
            return base.Channel.getAbsentsWithAliasByDateAsync(accesscode, date);
        }
        
        public string getAbsents(string accesscode, string userIdentifier, string schoolYear) {
            return base.Channel.getAbsents(accesscode, userIdentifier, schoolYear);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsAsync(string accesscode, string userIdentifier, string schoolYear) {
            return base.Channel.getAbsentsAsync(accesscode, userIdentifier, schoolYear);
        }
        
        public string getAbsentsWithAlias(string accesscode, string userIdentifier, string schoolYear) {
            return base.Channel.getAbsentsWithAlias(accesscode, userIdentifier, schoolYear);
        }
        
        public System.Threading.Tasks.Task<string> getAbsentsWithAliasAsync(string accesscode, string userIdentifier, string schoolYear) {
            return base.Channel.getAbsentsWithAliasAsync(accesscode, userIdentifier, schoolYear);
        }
        
        public string getUserDetails(string accesscode, string userIdentifier) {
            return base.Channel.getUserDetails(accesscode, userIdentifier);
        }
        
        public System.Threading.Tasks.Task<string> getUserDetailsAsync(string accesscode, string userIdentifier) {
            return base.Channel.getUserDetailsAsync(accesscode, userIdentifier);
        }
        
        public string getUserDetailsByNumber(string accesscode, string number) {
            return base.Channel.getUserDetailsByNumber(accesscode, number);
        }
        
        public System.Threading.Tasks.Task<string> getUserDetailsByNumberAsync(string accesscode, string number) {
            return base.Channel.getUserDetailsByNumberAsync(accesscode, number);
        }
        
        public string getUserDetailsByUsername(string accesscode, string username) {
            return base.Channel.getUserDetailsByUsername(accesscode, username);
        }
        
        public System.Threading.Tasks.Task<string> getUserDetailsByUsernameAsync(string accesscode, string username) {
            return base.Channel.getUserDetailsByUsernameAsync(accesscode, username);
        }
        
        public string getUserDetailsByScannableCode(string accesscode, string scannableCode) {
            return base.Channel.getUserDetailsByScannableCode(accesscode, scannableCode);
        }
        
        public System.Threading.Tasks.Task<string> getUserDetailsByScannableCodeAsync(string accesscode, string scannableCode) {
            return base.Channel.getUserDetailsByScannableCodeAsync(accesscode, scannableCode);
        }
        
        public string getUserOfficialClass(string accesscode, string userIdentifier, string date) {
            return base.Channel.getUserOfficialClass(accesscode, userIdentifier, date);
        }
        
        public System.Threading.Tasks.Task<string> getUserOfficialClassAsync(string accesscode, string userIdentifier, string date) {
            return base.Channel.getUserOfficialClassAsync(accesscode, userIdentifier, date);
        }
        
        public bool saveSignature(string accesscode, string userIdentifier, int accountType, string signature) {
            return base.Channel.saveSignature(accesscode, userIdentifier, accountType, signature);
        }
        
        public System.Threading.Tasks.Task<bool> saveSignatureAsync(string accesscode, string userIdentifier, int accountType, string signature) {
            return base.Channel.saveSignatureAsync(accesscode, userIdentifier, accountType, signature);
        }
        
        public string getStudentCareer(string accesscode, string userIdentifier) {
            return base.Channel.getStudentCareer(accesscode, userIdentifier);
        }
        
        public System.Threading.Tasks.Task<string> getStudentCareerAsync(string accesscode, string userIdentifier) {
            return base.Channel.getStudentCareerAsync(accesscode, userIdentifier);
        }
        
        public object deactivateTwoFactorAuthentication(string accesscode, string userIdentifier, int accountType) {
            return base.Channel.deactivateTwoFactorAuthentication(accesscode, userIdentifier, accountType);
        }
        
        public System.Threading.Tasks.Task<object> deactivateTwoFactorAuthenticationAsync(string accesscode, string userIdentifier, int accountType) {
            return base.Channel.deactivateTwoFactorAuthenticationAsync(accesscode, userIdentifier, accountType);
        }
        
        public void returnErrorCodes() {
            base.Channel.returnErrorCodes();
        }
        
        public System.Threading.Tasks.Task returnErrorCodesAsync() {
            return base.Channel.returnErrorCodesAsync();
        }
        
        public string returnCsvErrorCodes() {
            return base.Channel.returnCsvErrorCodes();
        }
        
        public System.Threading.Tasks.Task<string> returnCsvErrorCodesAsync() {
            return base.Channel.returnCsvErrorCodesAsync();
        }
        
        public string returnJsonErrorCodes() {
            return base.Channel.returnJsonErrorCodes();
        }
        
        public System.Threading.Tasks.Task<string> returnJsonErrorCodesAsync() {
            return base.Channel.returnJsonErrorCodesAsync();
        }
        
        public string startSkoreSync(string accesscode) {
            return base.Channel.startSkoreSync(accesscode);
        }
        
        public System.Threading.Tasks.Task<string> startSkoreSyncAsync(string accesscode) {
            return base.Channel.startSkoreSyncAsync(accesscode);
        }
        
        public string checkStatus(string accesscode, string serviceId) {
            return base.Channel.checkStatus(accesscode, serviceId);
        }
        
        public System.Threading.Tasks.Task<string> checkStatusAsync(string accesscode, string serviceId) {
            return base.Channel.checkStatusAsync(accesscode, serviceId);
        }
        
        public int changeUsername(string accesscode, string internNumber, string newUsername) {
            return base.Channel.changeUsername(accesscode, internNumber, newUsername);
        }
        
        public System.Threading.Tasks.Task<int> changeUsernameAsync(string accesscode, string internNumber, string newUsername) {
            return base.Channel.changeUsernameAsync(accesscode, internNumber, newUsername);
        }
        
        public int changeInternNumber(string accesscode, string username, string newInternNumber) {
            return base.Channel.changeInternNumber(accesscode, username, newInternNumber);
        }
        
        public System.Threading.Tasks.Task<int> changeInternNumberAsync(string accesscode, string username, string newInternNumber) {
            return base.Channel.changeInternNumberAsync(accesscode, username, newInternNumber);
        }
        
        public int changeGroupOwners(string accesscode, string code, string userlist) {
            return base.Channel.changeGroupOwners(accesscode, code, userlist);
        }
        
        public System.Threading.Tasks.Task<int> changeGroupOwnersAsync(string accesscode, string code, string userlist) {
            return base.Channel.changeGroupOwnersAsync(accesscode, code, userlist);
        }
        
        public object removeCoAccount(string accesscode, string userIdentifier, int accountType) {
            return base.Channel.removeCoAccount(accesscode, userIdentifier, accountType);
        }
        
        public System.Threading.Tasks.Task<object> removeCoAccountAsync(string accesscode, string userIdentifier, int accountType) {
            return base.Channel.removeCoAccountAsync(accesscode, userIdentifier, accountType);
        }
        
        public object getSchoolyearDataOfClass(string accesscode, string classCode) {
            return base.Channel.getSchoolyearDataOfClass(accesscode, classCode);
        }
        
        public System.Threading.Tasks.Task<object> getSchoolyearDataOfClassAsync(string accesscode, string classCode) {
            return base.Channel.getSchoolyearDataOfClassAsync(accesscode, classCode);
        }
        
        public object saveSchoolyearDataOfClass(string accesscode, string classCode, string date, string instituteNumber, string administrativeGroupNumber, string residence, string domain, string principal) {
            return base.Channel.saveSchoolyearDataOfClass(accesscode, classCode, date, instituteNumber, administrativeGroupNumber, residence, domain, principal);
        }
        
        public System.Threading.Tasks.Task<object> saveSchoolyearDataOfClassAsync(string accesscode, string classCode, string date, string instituteNumber, string administrativeGroupNumber, string residence, string domain, string principal) {
            return base.Channel.saveSchoolyearDataOfClassAsync(accesscode, classCode, date, instituteNumber, administrativeGroupNumber, residence, domain, principal);
        }
        
        public object getDeliberationLines(string accesscode, string dateInSchoolYear) {
            return base.Channel.getDeliberationLines(accesscode, dateInSchoolYear);
        }
        
        public System.Threading.Tasks.Task<object> getDeliberationLinesAsync(string accesscode, string dateInSchoolYear) {
            return base.Channel.getDeliberationLinesAsync(accesscode, dateInSchoolYear);
        }
        
        public object addHelpdeskTicket(string accesscode, string title, string description, int priority, string miniDbItem, string userIdentifier) {
            return base.Channel.addHelpdeskTicket(accesscode, title, description, priority, miniDbItem, userIdentifier);
        }
        
        public System.Threading.Tasks.Task<object> addHelpdeskTicketAsync(string accesscode, string title, string description, int priority, string miniDbItem, string userIdentifier) {
            return base.Channel.addHelpdeskTicketAsync(accesscode, title, description, priority, miniDbItem, userIdentifier);
        }
        
        public object getHelpdeskMiniDbItems(string accesscode) {
            return base.Channel.getHelpdeskMiniDbItems(accesscode);
        }
        
        public System.Threading.Tasks.Task<object> getHelpdeskMiniDbItemsAsync(string accesscode) {
            return base.Channel.getHelpdeskMiniDbItemsAsync(accesscode);
        }
    }
}
